### ISSUE TITLE
แจ้ง แก้ข้อ ที่ผิด

### ISSUE THREAD

**Issue by SitthaKlaphanich** [03376836-OOP-2566/03376836-OOP-2566-Lab-04#1]
**แก้ไข**  ข้อ 6 บันทึกผลที่ได้จากการรันคำสั่งใน ข้อ 5 
**ไม่ใช่ บันทึกผลที่ได้จากการรันคำสั่งในข้อ 4**
![image](https://github.com/03376836-OOP-2566/03376836-OOP-2566-Lab-04/assets/144195906/06bf02d7-6a88-4987-90d8-55ef4dcc2879)

**Comment by koson** [comment]
แก้เรียบร้อยแล้วครับ
